### ISSUE TITLE
F*ck you whatsapp, just 🖕

### ISSUE THREAD

**Issue by RaitaroH** [RaitaroH/WhatsApp-DeepDark#1]
No, seriously, just f*ck whoever is maintaining the whatsapp browser app. 🖕

The problem? Randomly generated selectors that change constantly.

Yo, @tkosamja, and you thought reddit was hard to make a theme for, nope THIS IS IT. OBV, making a theme the normal way is pointless, I have to go * and whitelist afterwards.

**Comment by tkosamja** [comment]
Never used Whatsapp web but that looks bad ahah why don't you try contacting the devs?

**Comment by RaitaroH** [comment]
XD, like they would give a shit.

**Comment by tkosamja** [comment]
You'll never know if you don't try :)

**Comment by RaitaroH** [comment]
@tkosamja Check the latest commit. I never went so global before.

**Comment by tkosamja** [comment]
LOL so much work for a little thing

**Comment by RaitaroH** [comment]
Half the theme was broken tho, they changed idk what... some selectors from makes sence to wtf.
