### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by tkosamja** [RaitaroH/WhatsApp-DeepDark#2]
So if I want to use WhatApp Web, the following appears:

![1](https://user-images.githubusercontent.com/26143003/36857142-aaa94e8c-1d6f-11e8-9102-76c0987b778c.PNG)
and it works just fine.

But if I'm using your theme, the phone can't read the QR Code since the logo in the middle gets themed:
![2](https://user-images.githubusercontent.com/26143003/36857162-bcf5c340-1d6f-11e8-832f-8146333ce5f3.PNG)

**Comment by RaitaroH** [comment]
XD Nice one.

**Comment by RaitaroH** [comment]
@tkosamja  Actually does this work?

**Comment by tkosamja** [comment]
This what?

**Comment by tkosamja** [comment]
The logo looks good now but my phone still can't read the QR code.

**Comment by vednoc** [comment]
It's not the logo that's causing the issue, it's the QR code. The image needs to have a white border around it to separate the dark parts from the background of your style. I believe any border color would do it, but use white just in case.

Here's how it looks in my style:
![image](https://i.imgur.com/lRCcp3k.png)

**Comment by RaitaroH** [comment]
Thanks @vednoc for the border idea.
